
import React, { useState } from 'react';
import { UserRole, User, Supplier, Material, ProcurementRecord, EnergyRecord } from './types';
import { INITIAL_USERS, INITIAL_SUPPLIERS, INITIAL_MATERIALS, INITIAL_PROCUREMENT, INITIAL_ENERGY } from './constants';
import Sidebar from './components/Sidebar';
import Dashboard from './views/Dashboard';
import MasterData from './views/MasterData';
import DataManagement from './views/DataManagement';
import RecommendationEngine from './views/RecommendationEngine';

const App: React.FC = () => {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [activeTab, setActiveTab] = useState('dashboard');
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  const [showUserModal, setShowUserModal] = useState(false);
  const [loginError, setLoginError] = useState<string | null>(null);
  
  // App State
  const [suppliers, setSuppliers] = useState<Supplier[]>(INITIAL_SUPPLIERS);
  const [materials, setMaterials] = useState<Material[]>(INITIAL_MATERIALS);
  const [procurement, setProcurement] = useState<ProcurementRecord[]>(INITIAL_PROCUREMENT);
  const [energy, setEnergy] = useState<EnergyRecord[]>(INITIAL_ENERGY);
  const [users, setUsers] = useState<User[]>(INITIAL_USERS);

  // Auth logic
  const [loginInput, setLoginInput] = useState({ username: '', role: UserRole.ADMIN });

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    setLoginError(null);
    const enteredUsername = loginInput.username.trim().toLowerCase();
    
    if (!enteredUsername) {
      setLoginError("Username is required.");
      return;
    }

    const userExists = users.some(u => u.username.toLowerCase() === enteredUsername);
    if (!userExists) {
      setLoginError(`User "${loginInput.username}" not found. Create it via Admin first.`);
      return;
    }

    const validUserWithRole = users.find(u => u.username.toLowerCase() === enteredUsername && u.role === loginInput.role);
    if (validUserWithRole) {
      setCurrentUser(validUserWithRole);
    } else {
      setLoginError(`"${loginInput.username}" is not registered as a ${loginInput.role.replace('_', ' ')}.`);
    }
  };

  const handleLogout = () => {
    setCurrentUser(null);
    setLoginError(null);
    setLoginInput({ username: '', role: UserRole.ADMIN });
    setActiveTab('dashboard');
  };

  const addProcurement = (p: Omit<ProcurementRecord, 'id'>) => {
    setProcurement(prev => [{ ...p, id: `p-${Date.now()}` }, ...prev]);
  };

  const addEnergy = (e: Omit<EnergyRecord, 'id'>) => {
    setEnergy(prev => [{ ...e, id: `e-${Date.now()}` }, ...prev]);
  };

  const manageSupplier = (supplier: Supplier, mode: 'add' | 'edit' | 'delete') => {
    if (mode === 'add') setSuppliers(prev => [...prev, supplier]);
    if (mode === 'edit') setSuppliers(prev => prev.map(s => s.id === supplier.id ? supplier : s));
    if (mode === 'delete') setSuppliers(prev => prev.filter(s => s.id !== supplier.id));
  };

  const manageMaterial = (material: Material, mode: 'add' | 'edit' | 'delete') => {
    if (mode === 'add') setMaterials(prev => [...prev, material]);
    if (mode === 'edit') setMaterials(prev => prev.map(m => m.id === material.id ? material : m));
    if (mode === 'delete') setMaterials(prev => prev.filter(m => m.id !== material.id));
  };

  const handleCreateUser = (e: React.FormEvent) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget as HTMLFormElement);
    const username = (formData.get('username') as string).trim();
    const role = formData.get('role') as UserRole;

    if (!username) return alert("User name is required.");
    if (users.some(u => u.username.toLowerCase() === username.toLowerCase())) {
        return alert("This username is already taken.");
    }

    const newUser: User = {
      id: `u-${Date.now()}`,
      username: username,
      role: role
    };

    setUsers(prev => [...prev, newUser]);
    setShowUserModal(false);
  };

  const deleteUser = (user: User) => {
    if (user.id === currentUser?.id) return alert("Cannot delete currently logged-in user.");
    if (confirm(`Remove access for "${user.username}"?`)) {
      setUsers(prev => prev.filter(u => u.id !== user.id));
    }
  };

  const handleGenerateReport = () => {
    setIsGeneratingReport(true);
    setTimeout(() => {
      const energyCarbon = energy.reduce((sum, e) => sum + e.carbonEquivalent, 0);
      const materialCarbon = procurement.reduce((sum, p) => {
        const mat = materials.find(m => m.id === p.materialId);
        return sum + (p.quantity * (mat?.carbonFactor || 0));
      }, 0);
      
      const reportData = [
        ["Annual Sustainability Report", "2024"],
        ["Generated By", currentUser?.username || "System"],
        [""],
        ["Total Footprint", (energyCarbon + materialCarbon) + " kg CO2e"]
      ];

      const csvContent = reportData.map(e => e.join(",")).join("\n");
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = `sustainability_report.csv`;
      link.click();
      setIsGeneratingReport(false);
      alert('Report generated!');
    }, 1500);
  };

  const renderContent = () => {
    if (!currentUser) return null;
    switch(activeTab) {
      case 'dashboard':
        return <Dashboard suppliers={suppliers} materials={materials} procurement={procurement} energy={energy} currentUser={currentUser} />;
      case 'master-data':
        return <MasterData suppliers={suppliers} materials={materials} onSupplierAction={manageSupplier} onMaterialAction={manageMaterial} />;
      case 'data-management':
        return <DataManagement materials={materials} suppliers={suppliers} procurement={procurement} energy={energy} currentRole={currentUser.role} onAddProcurement={addProcurement} onAddEnergy={addEnergy} />;
      case 'recommendations':
        return <RecommendationEngine suppliers={suppliers} materials={materials} procurement={procurement} />;
      case 'reports':
        return (
          <div className="flex flex-col items-center justify-center py-24">
             <div className="w-20 h-20 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mb-6">
                <i className={`fa-solid ${isGeneratingReport ? 'fa-spinner animate-spin' : 'fa-file-pdf'} text-3xl`}></i>
             </div>
             <h3 className="text-xl font-bold">Generate System Report</h3>
             <button onClick={handleGenerateReport} disabled={isGeneratingReport} className="mt-4 bg-emerald-600 text-white px-8 py-3 rounded-xl font-bold shadow-lg">
               {isGeneratingReport ? 'Processing...' : 'Download Report'}
             </button>
          </div>
        );
      case 'users':
        return (
          <div className="bg-white p-8 rounded-2xl border shadow-sm max-w-4xl mx-auto">
             <div className="flex justify-between items-center mb-8">
                <div>
                  <h3 className="text-2xl font-bold">Manage Personnel</h3>
                  <p className="text-slate-500 text-sm">Assign roles to allow specific users to log in.</p>
                </div>
                <button onClick={() => setShowUserModal(true)} className="bg-slate-900 text-white px-5 py-2.5 rounded-xl font-bold">Add User</button>
             </div>
             <div className="divide-y border-t">
               {users.map(u => (
                 <div key={u.id} className="py-4 flex justify-between items-center px-2">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center font-bold text-slate-500">{u.username.charAt(0).toUpperCase()}</div>
                      <div>
                        <p className="font-bold">{u.username}</p>
                        <p className="text-xs text-slate-400 font-bold uppercase">{u.role.replace('_', ' ')}</p>
                      </div>
                    </div>
                    <button onClick={() => deleteUser(u)} className="text-slate-300 hover:text-rose-500 p-2"><i className="fa-solid fa-trash"></i></button>
                 </div>
               ))}
             </div>
             {showUserModal && (
               <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
                 <div className="bg-white w-full max-w-md rounded-3xl p-8 shadow-2xl animate-in zoom-in duration-200">
                    <h3 className="text-2xl font-bold mb-6">Create System User</h3>
                    <form onSubmit={handleCreateUser} className="space-y-4">
                      <div className="space-y-1">
                        <label className="text-xs font-bold text-slate-500 uppercase">User Name</label>
                        <input name="username" required className="w-full border border-slate-200 p-3 rounded-xl outline-none" placeholder="e.g. Rahul" />
                      </div>
                      <div className="space-y-1">
                        <label className="text-xs font-bold text-slate-500 uppercase">System Role</label>
                        <select name="role" required className="w-full border border-slate-200 p-3 rounded-xl outline-none">
                          <option value={UserRole.PROCUREMENT_MANAGER}>Procurement Manager</option>
                          <option value={UserRole.SUSTAINABILITY_MANAGER}>Sustainability Manager</option>
                          <option value={UserRole.ADMIN}>Administrator</option>
                        </select>
                      </div>
                      <div className="flex gap-3 mt-8">
                        <button type="button" onClick={() => setShowUserModal(false)} className="flex-1 py-3 rounded-xl border font-bold">Cancel</button>
                        <button type="submit" className="flex-1 bg-emerald-600 text-white py-3 rounded-xl font-bold">Create User</button>
                      </div>
                    </form>
                 </div>
               </div>
             )}
          </div>
        );
      default: return <Dashboard suppliers={suppliers} materials={materials} procurement={procurement} energy={energy} currentUser={currentUser} />;
    }
  };

  if (!currentUser) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center p-4">
        <div className="bg-white w-full max-w-md rounded-3xl p-8 shadow-2xl animate-in zoom-in duration-300">
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-emerald-100 text-emerald-600 rounded-2xl flex items-center justify-center text-3xl mx-auto mb-4">
              <i className="fa-solid fa-leaf"></i>
            </div>
            <h1 className="text-3xl font-extrabold text-slate-900">Green ERP</h1>
            <p className="text-slate-500 mt-2 font-medium">Sustainability Decision Support</p>
          </div>

          <form onSubmit={handleLogin} className="space-y-5">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Username</label>
              <input 
                type="text" 
                className={`w-full bg-slate-50 border p-4 rounded-xl outline-none transition-all font-medium ${loginError ? 'border-rose-400 ring-2 ring-rose-50' : 'border-slate-100 focus:ring-2 focus:ring-emerald-500'}`}
                placeholder="Enter registered name"
                value={loginInput.username}
                onChange={e => { setLoginInput({...loginInput, username: e.target.value}); setLoginError(null); }}
              />
              {loginError && <p className="text-rose-500 text-xs font-bold ml-1 animate-pulse"><i className="fa-solid fa-circle-exclamation mr-1"></i> {loginError}</p>}
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Select Role</label>
              <div className="grid grid-cols-1 gap-2">
                {[UserRole.ADMIN, UserRole.PROCUREMENT_MANAGER, UserRole.SUSTAINABILITY_MANAGER].map(role => (
                  <button
                    key={role}
                    type="button"
                    onClick={() => { setLoginInput({...loginInput, role}); setLoginError(null); }}
                    className={`text-left px-4 py-3 rounded-xl border text-sm font-semibold transition-all ${
                      loginInput.role === role ? 'border-emerald-500 bg-emerald-50 text-emerald-700' : 'border-slate-100 bg-slate-50 text-slate-400 hover:border-emerald-200'
                    }`}
                  >
                    <i className={`fa-solid ${role === UserRole.ADMIN ? 'fa-user-shield' : role === UserRole.PROCUREMENT_MANAGER ? 'fa-truck-ramp-box' : 'fa-seedling'} mr-2`}></i>
                    {role.replace('_', ' ')}
                  </button>
                ))}
              </div>
            </div>

            <button type="submit" className="w-full bg-slate-900 text-white py-4 rounded-xl font-bold text-lg hover:bg-emerald-600 transition-all shadow-xl flex items-center justify-center gap-2">
              Sign In <i className="fa-solid fa-arrow-right"></i>
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <Sidebar currentRole={currentUser.role} activeTab={activeTab} setActiveTab={setActiveTab} onLogout={handleLogout} />
      <main className="pl-64 min-h-screen">
        <div className="p-10 max-w-[1400px] mx-auto">{renderContent()}</div>
      </main>
    </div>
  );
};

export default App;
